server:
    port: 8887
info:
    build:
        name: '@project.artifactId@'
        version: '@project.version@'
        time: '@git.build.time@'

spring:
    application:
        name: ${info.build.name}
    profiles:
        active: native

logging:
    level:
        com.github.aha.poc.micro: 'DEBUG'