spring:
    jackson:
        serialization:
            INDENT_OUTPUT: true    
 
logging:
    level:
        com.github.aha.poc.micro: 'DEBUG'

foo: aha

config:
    client:
        name: Arny