server:
    port: 8888

info:
    build:
        name: '@project.artifactId@'
        version: '@project.version@'
        time: '@git.build.time@'

spring:
    boot:
        admin:
            url: http://localhost:8888
    cloud:
        config:
            server:
                prefix: /config
    jackson:
        serialization:
            INDENT_OUTPUT: true
    profiles:
        active: native

logging:
    level:
        com.github.aha.poc.micro: 'DEBUG'