server:
    port: 8090

spring:
    application:
        name: ${info.build.name}
    boot:
        admin:
            url: http://localhost:8888
    jpa:
        generate-ddl: false
        show-sql: true
        hibernate:
            ddl-auto: none
    jackson:
        serialization:
            INDENT_OUTPUT: true

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost
        # improve service registration (for POC only)
        leaseRenewalIntervalInSeconds: 3
        metadataMap:
            instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.sql
    
logging:
    level:
        com.github.aha.poc.micro: 'DEBUG'