server:
    port: 8088

spring:
    boot:
        admin:
            url: http://localhost:8888
    jackson:
        serialization:
            INDENT_OUTPUT: true    
 
logging:
    leve:
        com.github.aha.poc.micro: 'DEBUG'

foo: aha

config:
    client:
        name: Arny