server:
    port: 8088

config:
    client:
        name: Arny
spring:
    boot:
        admin:
            url: http://localhost:8888
    jackson:
        serialization:
            INDENT_OUTPUT: true    
    jpa:
        generate-ddl: false
        show-sql: true
        hibernate:
            ddl-auto: none
 
logging:
    leve:
        com.github.aha.poc.micro: 'DEBUG'

foo: aha