info:
    build:
        name: '@project.artifactId@'
        version: '@project.version@'
        time: '@git.build.time@'
        
server:
    port: 8761

spring:
    application:
        name: ${info.build.name}
        
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
logging:
    level:
        com.github.aha.poc.micro: 'DEBUG'